// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ImageUploadController from "./image_upload_controller"
application.register("image-upload", ImageUploadController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import PlaceController from "./place_controller"
application.register("place", PlaceController)

import PlacesController from "./places_controller"
application.register("places", PlacesController)

import ReservationController from "./reservation_controller"
application.register("reservation", ReservationController)

import StarReviewController from "./star_review_controller"
application.register("star-review", StarReviewController)
