// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MenuController from "./menu_controller"
import PlaceController from "./place_controller"
import ImageUploadController from "./image_upload_controller"
import PlacesController from "./places_controller"

application.register("menu", MenuController)
application.register("place", PlaceController)
application.register("image-upload", ImageUploadController)
application.register("places", PlacesController)
